services:
  - type: web
    name: doot-secure-chat
    runtime: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
